name: Build LiquidBounce from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Unzip source
      run: unzip LiquidBounce-Fabric-1.21.1_SafeGL-Mobile.zip

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x LiquidBounce-Fabric-1.21.1_SafeGL-Mobile/gradlew

    - name: Build with Gradle
      run: cd LiquidBounce-Fabric-1.21.1_SafeGL-Mobile && ./gradlew build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: LiquidBounce-Build
        path: LiquidBounce-Fabric-1.21.1_SafeGL-Mobile/build/libs/*.jar
