name: Build LiquidBounce JAR

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Unzip source
        run: unzip LiquidBounce-nextgen_SafeGL3_patch.zip -d source

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: source/LiquidBounce-nextgen

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: source/LiquidBounce-nextgen

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liquidbounce-jar
          path: source/LiquidBounce-nextgen/**/build/libs/*.jar
