name: Build LiquidBounce from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Unzip source
        run: unzip -q "*.zip" -d source

      - name: Find gradlew & build
        run: |
          chmod +x $(find source -name gradlew)
          cd $(dirname $(find source -name gradlew))
          ./gradlew build --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LiquidBounce-Build
          path: |
            **/build/libs/*.jar
