name: Build LiquidBounce from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and unzip latest ZIP
        run: |
          ZIP_FILE=$(ls -t *.zip | head -n 1)
          echo "Found ZIP: $ZIP_FILE"
          unzip -q "$ZIP_FILE" -d source

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x $(find source -name gradlew)
          cd $(dirname $(find source -name gradlew))
          ./gradlew build --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LiquidBounce-Build
          path: |
            **/build/libs/*.jar
