name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting build job..."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip source
        run: unzip "*.zip" -d source

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x $(find . -name gradlew)

      - name: Build with Gradle
        run: $(find . -name gradlew) build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/build/libs/*.jar
