name: Build LiquidBounce

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Unzip source
        run: |
          mkdir source
          unzip "*.zip" -d source

      - name: Find gradle project
        run: |
          cd $(dirname $(find source -name gradlew))
          echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Fix Minecraft version
        run: |
          cd $PROJECT_DIR
          sed -i 's/^minecraft_version=.*/minecraft_version=1.21.1/' gradle.properties
          sed -i 's/^yarn_mappings=.*/yarn_mappings=1.21.1+build.1/' gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x $PROJECT_DIR/gradlew

      - name: Build with Gradle
        run: cd $PROJECT_DIR && ./gradlew build --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LiquidBounce-Build
          path: ${{ env.PROJECT_DIR }}/build/libs/*.jar
